name: BOSH SBoM internal Action
description: BOSH SBoM internal Action

inputs:
  slsa-workflow-inputs:
    description: 'All the inputs formatted as a map'
    type: string
    required: true

  slsa-layout-file:
    description: 'Location to store the layout content'
    type: string
    required: true
  
  # Unused secret inputs.
  slsa-workflow-secret1: {}
  slsa-workflow-secret2: {}
  slsa-workflow-secret3: {}
  slsa-workflow-secret4: {}
  slsa-workflow-secret5: {}
  slsa-workflow-secret6: {}
  slsa-workflow-secret7: {}
  slsa-workflow-secret8: {}
  slsa-workflow-secret9: {}
  slsa-workflow-secret10: {}
  slsa-workflow-secret11: {}
  slsa-workflow-secret12: {}
  slsa-workflow-secret13: {}
  slsa-workflow-secret14: {}
  slsa-workflow-secret15: {}

outputs:
  sbom:
    description: "go.mod SBoM for a given package in the provided BOSH release"
    value: "${{ steps.generate-go-sbom.outputs.sbom }}"

runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        repository: ${{ fromJson(inputs.slsa-workflow-inputs).repository }}

    - name: Download syft
      shell: bash
      run: |
        curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
        sudo chmod +x /usr/local/bin/syft

    - name: Run main Action
      uses: ./../__TOOL_CHECKOUT_DIR__/gomod_sbom
      id: generate-go-sbom
      with:
        go-mod: ${{ fromJson(inputs.slsa-workflow-inputs).go-mod }}
        sbom-format: ${{ fromJson(inputs.slsa-workflow-inputs).sbom-format }}

    - name: Generate layout file
      id: generate-layout
      env:
        SLSA_OUTPUTS_ARTIFACTS_FILE: ${{ inputs.slsa-layout-file }}
        SBOM: ${{ steps.generate-go-sbom.outputs.sbom }}
      shell: bash
      run: ./../__TOOL_ACTION_DIR__/generate_layout.sh