---
resources:
- name: bpm-release
  type: git
  source:
    uri: git@github.com:cloudfoundry/bpm-release.git
    branch: master
    private_key: ((signing_test.private_key))
- name: bosh-secure-supply-chain
  type: git
  source:
    uri: git@github.com:dtimm/bosh-secure-supply-chain.git
    branch: main
    private_key: ((signing_test.private_key))

jobs:
- name: generate-sbom-provenance
  serial: true
  plan:
  - in_parallel:
    - get: bpm-release
    - get: bosh-secure-supply-chain
  - task: generate-gomod-sbom
    file: bosh-secure-supply-chain/concourse/gomod/task.yml
    input_mapping:
      bosh-release: bpm-release
    params:
      COSIGN_KEY: ((signing_test.cosign_key))
      COSIGN_PASSWORD: ((signing_test.cosign_key_password))

