apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: bosh-release-ingest
  namespace: default
spec:
  taskRef:
    name: bosh-release-ingest
  params:
  - name: release-file
    value: releases/bpm/bpm-1.2.5.yml
  - name: bosh-release-uri
    value: https://github.com/dtimm/bpm-release.git