---
apiVersion: carto.run/v1alpha1
kind: ClusterSupplyChain
metadata:
  name: bosh-release-ingest
spec:
  selectorMatchFields:
  - key: apps.tanzu.vmware.com/workload-type
    operator: In
    values: [ bosh-release-ingest ]
  resources:
  - name: bosh-release-ingest
    templateRef:
      kind: ClusterTemplate
      name: bosh-release-ingest