name: BOSH SLSA

on:
  workflow_call:

jobs:
  find-supported-files:
    runs-on: ubuntu-latest
    outputs:
      gomods: ${{ steps.find-supported-files.outputs.gomods }}
      gemfiles: ${{ steps.find-supported-files.outputs.gemfiles }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: dtimm/bosh-secure-supply-chain
          path: bosh_link
          ref: main
      - name: Find supported files files
        id: find-supported-files
        run: bosh_link/scripts/find_supported_files.sh

  generate-gomod-attestation:
    needs: find-supported-files
    strategy:
      matrix:
        go-mod: ${{ fromJSON(needs.find-supported-files.outputs.gomods) }}
    permissions:
      id-token: write # For signing
      contents: write # For asset release.
      packages: write # For package upload.
      actions: read # For getting workflow run info.
    uses: dtimm/bosh-secure-supply-chain/.github/workflows/go_vendor.yml@main
    with:
      go-mod: ${{ matrix.go-mod }}
